version: "3"
services:
  # サービス名
  app:
    # ./Dockerfileをビルドして使用
    build: 
      context: "."
    # コンテナの起動を維持する
    tty: true
    # ホストポート9000番をコンテナポート9000番に割り当てる
    ports:
      - 9000:9000
    # 一階層上のホストディレクトリをコンテナの/workspace/demo-remote-containerにマウントする
    volumes:
      - ../:/workspace/demo-remote-container
    # コンテナ内の環境変数の設定
    environment:
      DB_HOST: db

  db:
    image: mysql/mysql-server:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sample
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
      MYSQL_TCP_PORT: 3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8080:80
    # dbに依存させる
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=user
      - PMA_PASSWORD=password